import { Raleway, Barlow } from 'next/font/google'
import "./globals.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const ralewayFont = Raleway({
  variable: '--font-raleway',
  display: "swap",
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

const barlowFont = Barlow({
  variable: '--font-barlow',
  display: "swap",
  weight: ['400'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlowFont.variable} ${ralewayFont.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
